# Generated by Django 4.0 on 2022-02-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineStatus', models.CharField(max_length=150)),
                ('fuelLevel', models.CharField(max_length=150)),
                ('temperature', models.IntegerField()),
                ('averageSpeed', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
