# Generated by Django 4.0 on 2022-02-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
